apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  labels:
    app: nginxhello
  name: single-default-backend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
kubernetes.io/ingress.class: “nginx”
    fluxcd.io/ignore: "false"
spec:
  backend:
    serviceName: nginxhello
    servicePort: 80
