apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  labels:
    app: nginxhello
  name: single-default-backend-ingress
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    fluxcd.io/ignore: "false"
spec:
  backend:
    serviceName: nginxhello
    servicePort: 80
